/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantSlugRouteImport } from './routes/$tenantSlug'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SessionRouteImport } from './routes/session'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated.notes'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const TenantSlugRoute = TenantSlugRouteImport.update({
  id: '/$tenantSlug',
  path: '/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$tenantSlug': typeof TenantSlugRoute
  '/': typeof AuthenticatedIndexRoute
  '/session': typeof SessionRoute
  '/signin': typeof SigninRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/$tenantSlug': typeof TenantSlugRoute
  '/session': typeof SessionRoute
  '/signin': typeof SigninRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$tenantSlug': typeof TenantSlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/session': typeof SessionRoute
  '/signin': typeof SigninRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$tenantSlug'
    | '/'
    | '/session'
    | '/signin'
    | '/notes'
    | '/api/$'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$tenantSlug'
    | '/session'
    | '/signin'
    | '/notes'
    | '/api/$'
    | '/auth/callback'
    | '/'
  id:
    | '__root__'
    | '/$tenantSlug'
    | '/_authenticated'
    | '/session'
    | '/signin'
    | '/_authenticated/notes'
    | '/api/$'
    | '/auth/callback'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TenantSlugRoute: typeof TenantSlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SessionRoute: typeof SessionRoute
  SigninRoute: typeof SigninRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$tenantSlug': {
      id: '/$tenantSlug'
      path: '/$tenantSlug'
      fullPath: '/$tenantSlug'
      preLoaderRoute: typeof TenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TenantSlugRoute: TenantSlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SessionRoute: SessionRoute,
  SigninRoute: SigninRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
